name: Movies CRON

on:
  schedule: # runs on the 1st of every month
    - cron: "0 0 1 * *"
  workflow_dispatch: # to allow re-runs from the github ui

permissions:
  contents: write

jobs:
  fetch-movies:
    runs-on: ubuntu-latest
    name: Renewing Data
    env:
      TMDB_API_KEY: ${{secrets.TMDB_API_KEY}}
    steps:
      - name: checking out code
        uses: actions/checkout@v5

      - name: setting up python
        uses: actions/setup-python@v5

      - name: Installing deps # requests is the only dep
        run: pip install requests

      - name: run python script # this should return a movies.json file at root
        run: python3 ./scripts/fetch_movies.py

      - name: upload generated file as artifact
        uses: actions/upload-artifact@v4
        with:
          name: movies # folder name
          path: ./movies.json # path to the generated file.

      - name: Move generated file # replace the old file
        run: mv ./movies.json ./src/assets/final_movies_v4.json

      - name: Commit and Push changes
        run: |
          git config --global user.name "github-action's bot"
          git config --global user.email "fake@mail.com"
          git add ./src/assets/final_movies_v4.json 
          git commit -m 'Automated Commit - refreshing movies'
          git push
  update-database:
    runs-on: ubuntu-latest
    name: update embedding in db
    needs: fetch-movies

    steps:
      - name: download the artifact
        uses: actions/download-artifact@v4
        with:
          name: movies
    
      - name: install jq for json manipulation
        run: sudo apt install -y jq
    
      - name: split the json file into chunks
        run: |
          CHUNK_SIZE=1000
          ARRAY_LENGTH=$(jq '. | length' "movies.json")
          for ((i=0; i<$ARRAY_LENGTH; i+=CHUNK_SIZE)); do
            jq ".[$i:$((i+CHUNK_SIZE))]" movies.json > "chunk_$i.json"
          done
    
      - name: run the api endpoint
        run: |
          FULL_URL="${{ vars.API_URL }}/embed/batch"
          for chunk_file in chunk_*.json; do
            curl --request POST \
                 --url $FULL_URL \
                 --header 'Content-Type: application/json' \
                 --data-binary "@$chunk_file"
          done
